### ISSUE TITLE
New logo design  care of @Sotic on discord.

### ISSUE THREAD

**Issue by yosileyid** [hasidicdevs/hasidicdevs.github.io#3]
We need a nice new logo for the group. Sotic on discord offered to help. Lets vote on it or sum?

![Image](https://user-images.githubusercontent.com/14003326/217126672-6cbfa6d6-b9da-4f5f-99e5-14e20682cf12.jpeg)

**Comment by Smokeyoy** [comment]
very super epic

**Comment by yosileyid** [comment]
Nah... this the one. 



![Image](https://user-images.githubusercontent.com/14003326/217130219-292ffeee-d2c0-4824-8468-2b46eebd5803.png)
